# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetAAPI', '0003_auto_20170609_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetAAPI.Cocktail'),
        ),
    ]
