# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetAAPI', '0006_auto_20170703_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d5aeaef3-0a9c-4d16-b741-977d0c07497e'), editable=False, unique=True),
        ),
    ]
